### ISSUE TITLE
suggestion performance problems

### ISSUE THREAD

**Issue by turiartt** [ehynds/jquery-ui-multiselect-widget#157]
Hello, I experienced performance problems when more than 2000 options. To took an average of four minutes to assemble the combo (bad machines), not to mention when you click on or search.

modified the section:
this.element.find('option').each(function( i ){

changes:
- changed the "each" by classic "array".
- "html" var, is not an array, pass by simple string. Don't use ".push" and uses "+=";

with these changes, the time fell to below 1 minute.

Att,

**Comment by k2kkapoor** [comment]
I am facing performance issue on IE 11, can you send me the modified files as well at the earliest.

**Comment by mlh758** [comment]
@k2kkapoor You may want to use the latest versions from master here on Github. There has been 3 releases since this thread was opened in 2012 and some additional fixes beyond the latest release as well. The minified files haven't been updating with anything past 1.15 but you can minify them yourself if you need those last changes.

**Comment by k2kkapoor** [comment]
@mlh758 : Can you please provide me link to the latest multiselect.js and filter.js file.

**Comment by mlh758** [comment]
This is the GitHub repository for multiselect, so they're stored here, where you are currently commenting. This is a direct link within the repo though: https://github.com/ehynds/jquery-ui-multiselect-widget/tree/master/src

**Comment by mlh758** [comment]
I added another of the suggested fixes to the source code - looking up values by key instead of searching an array is a good idea. I'm not going to be swapping find for children however. In the years since this was opened find has become _much_ faster than children. There will be a commit incoming shortly for this.
