### ISSUE TITLE
Twitter Bootstrap Incompatible

### ISSUE THREAD

**Issue by megabga** [ehynds/jquery-ui-multiselect-widget#276]
If used ui-multiselect in bootstrap css environment, the options of widget get out of designed visual, and layout crashes.
May be, because resets and more heavy configurations provided by twitter bootstrap.

Thanks for advanced

**Comment by SteveTheTechie** [comment]
@mlh758 I wonder if there is a way to check this now w/ the version 3 changes.

**Comment by mlh758** [comment]
Would need to set up a small bootstrap page with some selects. Probably wouldn't be too hard to put together, especially if I can find a quick example page to drop it all onto.

**Comment by mlh758** [comment]
Added a bootstrap demo to my gist: https://gist.github.com/mlh758/b1b24931db7705441f9786bd68cf3569

It's still a little bit off, likely due to the aggressive resets in Bootstrap. I'm a little dubious of the need for this widget in Bootstrap though. It's a full framework, and they provide [their own](https://getbootstrap.com/docs/4.0/components/forms/#select-menu) look for using selects.

This widget requires jquery-ui and it's accompanying css, which is going to conflict with Bootstrap stuff. It's another tool that kind of removes the need for any of the jQuery stuff aside from the jquery thin library they pull in to back their tools.

**Comment by SteveTheTechie** [comment]
@mlh758 maybe just close this then.
