### ISSUE TITLE
Setting focus to the widget

### ISSUE THREAD

**Issue by nocarrier** [ehynds/jquery-ui-multiselect-widget#291]
In the multiselect source I added code to go to another control on tab key press. It works if the control is a textbox, radio, check, etc - but not if the ID i specify is a multiselect widget:

```
                   //var focusTarget = document.getElementById(o.nextControlId); <--- param i added
        var focusTarget = document.getElementById('Input_BrandIds');   // <-- this is another multislect; focus is on a different widget now.

        if(isDebug)
            console.log('focusTarget = ' + focusTarget + ' & nextControlId = ' + o.nextControlId);

        focusTarget.focus(); /// works if is textbox... :/
```

Do you know another method of getting access to another multiselect instance from within the currently focused object? Seems like this would work, but maybe I need to hit the label, button, or use some other accessor.

Thanks.

**Comment by danielowentorrey** [comment]
@anthonykeller79: Awesome solution! Worked perfectly.

**Comment by mlh758** [comment]
We've greatly improved keyboard navigation in some recent commits.

When closing the menu with esc or tab, the button for the multiselect is focused which lets you tab to the next element in the form in a natural manner.

You can also get the button element from the widget by using:

`$("select").multiselect("instance").button`

if you want to mess with it somehow.

I know this issue is pretty old but I figured this would be helpful to have for future reference.

**Comment by nocarrier** [comment]
Better late than never! Thanks!!
