### ISSUE TITLE
_setButtonValue should use .html instead of .text

### ISSUE THREAD

**Issue by hooverlunch** [ehynds/jquery-ui-multiselect-widget#473]
on line 225, the values to show in the button are gathered with:

value = $checked.map(function() { return $(this).next().html(); }).get().join(', ');

but then the button value is set with (on 239):

this.buttonlabel.text(value);

since one is .html and the other is .text, htmlentities show up raw (e.g. &amp) in the button label

**Comment by LouTerrailloune** [comment]
In the _create function `.html()` is used to set the label, this is not consistent. I think the best solution is to use HTML everywhere.

**Comment by mlh758** [comment]
HTML everywhere leaves the code more open to XSS vulnerabilities. The original developer intentionally set it this way to make the default behavior safe, if you need unsafe behavior then you can override the method and add html. There is documentation on how to do this in the the [Customization](https://github.com/ehynds/jquery-ui-multiselect-widget/wiki/Customization) section of the docs.

Since this issue was opened, the line described above was actually changed from `html()` to `text()` as well.
