### ISSUE TITLE
how to add an item to this widget which doesn't have or require text

### ISSUE THREAD

**Issue by hodgezappa** [ehynds/jquery-ui-multiselect-widget#570]
Apologies if this is a repeat of someone else's post. I needed to add an item to this widget that has no text but did belong to a top level optgroup (out of borough patients in my example) :
![01](https://cloud.githubusercontent.com/assets/6883862/3903539/3ae91de8-22cd-11e4-95dd-629ba2a50877.jpeg)
This caused a trailing comma to appear in the 'list of selected items' button text though when I had the out of borough patient option ticked.  

To fix this i added a bit of regex to remove the trailing comma, by changing this line in the update function from:
}).get().join(", "): a.selectedText.replace("#", f).replace("#", b.length);

to this:
 }).get().join(", ").replace(/^[\s,]+|[\s,]+$/g, '') : a.selectedText.replace("#", f).replace("#", b.length);

So is there a better way to do this?

thanks

**Comment by mlh758** [comment]
I don't think having blank items is a typical use case, and when it is I think the usual expectation would be for the items to still be returned in the text so there is an indication they are selected.

You could set the selectedListSeparator option to get some limited improvement for your specific case without code changes. Otherwise, I think your implementation is probably about as good as it will get.
