### ISSUE TITLE
Refresh not rebuilding the button text

### ISSUE THREAD

**Issue by rorliz** [ehynds/jquery-ui-multiselect-widget#585]
The select I am working with is hidden in a table tr at first.  Then once search parameters are entered, an ajax call retrieves a number of facilities.  The options are built and appended to the select as follows:

    $.each(return_fac, function(i,v) {
          if (return_fac[i].facility_group_id == 0) {
              var $option = $('<option />')
                    .attr('value', return_fac[i].fac_id)
                   .css('padding', '3px 0')
                    .html(return_fac[i].fac_info)
                    .appendTo($('select#fac_select'));
          }
    });
    $('tr#facilityChoices').show();
    $('select#fac_select').multiselect({buttonWidth: 550, menuWidth: 535, height: 150, noneSelectedText: 'Select Facility'});
    $("select#fac_select").multiselect('refresh');

The problem is that once an initial set of facilities is retrieved, if some are selected, then a different search parameter is entered and a different set of facilities returned, the options are all refreshed properly, however the button still shows "3 Selected".  How to get this button selection text to reset to the none selected text?

**Comment by mlh758** [comment]
The button text is rebuilt upon calling refresh. If there are still selected items, it will stay say "# Selected".

If you want a gaurantee that everything is reset when you reload all the options you can do the following:

    $('select#fac_select').empty();
    $('select#fac_select').multiselect("refresh");
    //Your code to add new items to the select
    $('select#fac_select').multiselect("refresh");

By emptying the select and refreshing you will guarantee the button text is reset to the none selected value. This shouldn't be necessary however, it is more likely that some items remain in the select list, still selected whe you append the new items. Especially since in your code you are only appending new items and not removing the old.
