### ISSUE TITLE
How to dynamically group items in asp.net

### ISSUE THREAD

**Issue by momer79** [ehynds/jquery-ui-multiselect-widget#596]
I am using multiselect widget on asp.net page. Items are added dynamically at run time from code behind page.

Is there any way to group items dynamically depeneds on the data in the database. It can be done through html by using optgroup label but can't fugure out how to do it at run time from code behind the page.

    <script type="text/javascript">
    $(function () {

        $("#uc_ddlmultiselect select").multiselect({
            //multiple: true,
            //header: "",
            noneSelectedText: "-- View All --",
            selectedList: 10
        });

    });

  </script>

      <body>
        <asp:ListBox ID="ddl" SelectionMode="Multiple" runat="server" ></asp:ListBox>
       </body>

Code Behind Page

Public Sub BindList(Of T)(ByVal list As IEnumerable(Of T), ByVal DataTextField As String, ByVal DataValueField As String)
    ddl.Items.Clear()
    ddl.DataSource = list

    ddl.DataTextField = DataTextField 
    ddl.DataValueField = DataValueField
    ddl.DataBind()
End Sub

**Comment by mlh758** [comment]
You can update the `<select>` on the page when your back end code returns new values. Then you just call the `refresh` multiselect method and it will update the widget with the new elements. `<optgroup>` tags are honored by the multiselect widget, although I would suggest using the latest code from master since it resolves a bug with clicking the label of the option group.
