### ISSUE TITLE
Numeric Sort Order

### ISSUE THREAD

**Issue by LivDieRepeat** [ehynds/jquery-ui-multiselect-widget#618]
Multiselect-widget is incorporated in a script I have, and it pulls data from a database.
The Sort order of the select choices show up as:

Option:
1
10
100
101
102
etc.

Instead of:
1
2
3
4
5
etc.

Might someone know if/how I can fix this.
Im a noob and really appreciate your help.

incorporated in the script is version 1.12
thanks

**Comment by mlh758** [comment]
This is happening because the default sort order in JavaScript is always alphabetical.

http://stackoverflow.com/questions/1063007/how-to-sort-an-array-of-integers-correctly

This is a JavaScript issue, not an issue with the multiselect. Pass `sort()` a custom comparison function like in the stack overflow example and you won't have an issue anymore.
