### ISSUE TITLE
HTML special characters

### ISSUE THREAD

**Issue by uwekolsch** [ehynds/jquery-ui-multiselect-widget#633]
On line 226 in jquery.multiselect.js
value = $checked.map(function() { return $(this).next().html(); }).get().join(', ');

the use of .html() converts special html characters like &, <, > to the html code representing it and shows it, so the entry 'Foo & Foe' in the select list becomes 'Foo &amp; Foo' on selection. 

Changing it to .text() avoids the problem, though not sure if it has other implications.

**Comment by mlh758** [comment]
This was fixed with a [recent pull request](https://github.com/ehynds/jquery-ui-multiselect-widget/pull/442). This makes it much more difficult for users to embed HTML into the text of the button label by overriding `_setButtonValue`, but not impossible. I think this benefits the use case of more users.
