### ISSUE TITLE
generated button is missing 'id' and 'name' attributes

### ISSUE THREAD

**Issue by jjdunn** [ehynds/jquery-ui-multiselect-widget#641]
for automated testing (e.g. using Selenium) we often need to select an element by name or id.  It's impossible since the generated button has no 'name' nor 'id' attribute.

patch in jquery.multiselect.js _create()
```
var elid = this.element.attr("id") + "_ms"; //+JJD
button = (this.button = $('<button type="button" id="'+elid+'"><span class="ui-icon ui-icon-triangle-2-n-s"></span></button>'))
```

**Comment by mlh758** [comment]
Have you considered setting a title attribute on the element you are making the widget from?
`<select ...title="something"><option>First</option></select>`

This should add a title to the button that you could select from without having to make any code changes.

**Comment by jjdunn** [comment]
> Have you considered setting a title attribute on the element you are making the widget from?
it's a production application.  the "title" attribute is visible on hover, and we don't want it to be visible to users.

**Comment by mlh758** [comment]
I'll have a fix up for you soon.

**Comment by jjdunn** [comment]
> I'll have a fix up for you soon.
thanks for your attentiveness.  However I'm reasonably happy with the patch noted in the first comment; and since we're running some-old-version of multiselect, we probably won't take any recent changes right now; so no need to rush.   

I was just posting this patch to improve already-very-useful software, and so others could benefit.  :-)

**Comment by mlh758** [comment]
Ah, well either way, the change is up now along with a corresponding unit test. Thanks for bringing this up! The minified code is updated as well, 1.14 that was recently released has a number of bug fixes and an updated test harness. You might see something useful in there if you review the patch notes and recently merged pulls (there have been some changes since the last release).

Although if it's working for you, it's probably best not to fix what isn't broken...
