### ISSUE TITLE
Add option to use .html() instead of .text() to get option display and set checkbox span display for decoration purposes

### ISSUE THREAD

**Issue by gatsy97d** [ehynds/jquery-ui-multiselect-widget#696]
In line 197 of jquery.multiselect.js, when option isHtml is true instead of

$("<span/>").text($(option).text()).appendTo($label);

it will use

$("<span/>").html($(option).html()).appendTo($label);

**Comment by mlh758** [comment]
You're looking for an additional option to allow HTML in the option tags?

**Comment by gatsy97d** [comment]
Yes adding an option to use .html() instead of .text()
im still not familiar with contributing to github since I know where to update in the code.

**Comment by SteveTheTechie** [comment]
This will be included in version 3.   A new option has been created.

Additionally, an option has also been created for the button text.   For example, I like to make my button list separate be '<br>' so that each selected list item shows on a separate line and the button grows vertically (to some limit as set by selectedList).

**Comment by SteveTheTechie** [comment]
This issue can now be closed.   An option called htmlOptionText was added in the last pull request for version 3 that has been merged.
