### ISSUE TITLE
Bug: It can't work with jqueryui-dialog

### ISSUE THREAD

**Issue by youbl** [ehynds/jquery-ui-multiselect-widget#706]
when jqueryui dialog contains this multiselect, the list was covered by dialog!!!
I used this code to fix this bug:
`$('.ui-multiselect-menu').css('z-index',1000)`

**Comment by mlh758** [comment]
What version of the widget are you using?

**Comment by youbl** [comment]
jQuery MultiSelect UI Widget 2.0.1

**Comment by mlh758** [comment]
Does your dialog have custom classes on it? The menu should be automatically appended under any element with the `.ui-front` class on it.

You can also explicitly use the `appendTo` option on the widget to set where it goes. I'd recommend against using z-index for this since you'll inevitably end up in a z-index war with other libraries as different widgets vie for the top layer.
