### ISSUE TITLE
Changing multiple option clears selected values

### ISSUE THREAD

**Issue by mlh758** [ehynds/jquery-ui-multiselect-widget#712]
Conversation started in #377 breaking it out to a separate issue

At first glance this seems intentional, changing the multiple option would change the intent of the widget so clearing the options would be desired behavior. This is deliberately done in the handler for multiple.

However, @jasonperrone it seems like you're seeing a different issue. Your code is re-calling the initializer and this is clearing the values. Could you elaborate on that? Maybe provide a code snippet or a fiddle? I don't think I'm completely clear on your use case.

**Comment by jasonperrone** [comment]
Well I don't have a code sample handy but it's just this:
1) Start with a multi-select element, already initialized, filled with options, etc... Go ahead and initialize it to support multiples
2) Select some values with element.val("blah blah") and element.multiselect('refresh'); The values should show selected in the UI.
3) do element.multiselect({'multiple': true}), arguably an unnecessary thing to do, but just do it.
4) The values you previously had selected will unselect. Calling element.val() should return empty array.

**Comment by mlh758** [comment]
I think the resolution here will be to just do nothing with the `multiple` method if the value hasn't changed.

**Comment by jasonperrone** [comment]
I was thinking the same thing.

**Comment by SteveTheTechie** [comment]
Having this multiple method is very unwise, since it enables the widget to get functionally mis-aligned with the underlying select element.  I believe it is better to just set the multiple attribute on the select in the html, and have the widget check that attribute as part of its initialization.  This ensures that the underlying element and the widget are functionally aligned.

I recommend just ditching the internal multiple config and method and just fetching the attribute from the select element.

**Comment by SteveTheTechie** [comment]
I think this may be fixed in the version3 branch code that I am building out. 

You may want to download that code and check if it fixes your issue.

**Comment by SteveTheTechie** [comment]
@mlh758  Can you see if this is still an issue?  I think this can probably be closed.

**Comment by mlh758** [comment]
Appears to be fixed.
