### ISSUE TITLE
In Ipad widget doesn't close after clicking outside.

### ISSUE THREAD

**Issue by Datta-Telukunta** [ehynds/jquery-ui-multiselect-widget#861]
### What is the current behavior?
Widget doesn't close after clicking outside in Ipad.

### What is the expected behavior?
Widget should close after clicking outside in Ipad.

### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo
_Common options for demos are [jsfiddle](https://jsfiddle.net/) and [codepen](https://codepen.io)_

### Please tell us about your setup
  
  * Version: 1.14
  * Browser: Safari
  * Other frameworks in use:

**Comment by mlh758** [comment]
Unfortunately I don't own a tablet in order to reproduce this. Does the issue also happen on an iPhone version of Safari?

Also, are you able to upgrade to a more up to date version of the widget? If it is still present in 2.x or 3.x I'd be willing to work out a fix but I'm not going to back port a fix to 1.x.
